# Code generated by Lark OpenAPI.

from typing import *
from baseopensdk.core.construct import init
from .app_table_record_sort import AppTableRecordSort
from .app_table_record_filter import AppTableRecordFilterInfo


class SearchAppTableRecordRequestBody(object):
    _types = {
        "view_id": str,
        "field_names": list[str],
        "filter": AppTableRecordFilterInfo,
        "sort": list[AppTableRecordSort],
        "automatic_fields": bool,
    }

    def __init__(self, d=None):
        self.view_id: Optional[str] = None
        self.field_names: Optional[list[str]] = None
        self.filter: Optional[AppTableRecordFilterInfo] = None
        self.sort: Optional[list[AppTableRecordSort]] = None
        self.automatic_fields: bool = False
        init(self, d, self._types)

    @staticmethod
    def builder() -> "SearchAppTableRecordRequestBodyBuilder":
        return SearchAppTableRecordRequestBodyBuilder()


class SearchAppTableRecordRequestBodyBuilder(object):
    def __init__(self) -> None:
        self._search_app_table_record_request_body = SearchAppTableRecordRequestBody()

    def view_id(self, view_id: str) -> "SearchAppTableRecordRequestBodyBuilder":
        self._search_app_table_record_request_body.view_id = view_id
        return self

    def field_names(
        self, field_names: list[str]
    ) -> "SearchAppTableRecordRequestBodyBuilder":
        self._search_app_table_record_request_body.field_names = field_names
        return self

    def filter(
        self, filter: AppTableRecordFilterInfo
    ) -> "SearchAppTableRecordRequestBodyBuilder":
        self._search_app_table_record_request_body.filter = filter
        return self

    def sort(
        self, sort: list[AppTableRecordSort]
    ) -> "SearchAppTableRecordRequestBodyBuilder":
        self._search_app_table_record_request_body.sort = sort
        return self

    def automatic_fields(
        self, automatic_fields: bool
    ) -> "SearchAppTableRecordRequestBodyBuilder":
        self._search_app_table_record_request_body.automatic_fields = automatic_fields
        return self

    def build(self) -> "SearchAppTableRecordRequestBody":
        return self._search_app_table_record_request_body
