# Code generated by Lark OpenAPI.

from typing import *
from typing import IO
from baseopensdk.core.construct import init
from baseopensdk.api.base.v1.model.app_table_record import AppTableRecord


class SearchAppTableRecordResponseBody(object):
    _types = {
        "has_more": bool,
        "page_token": str,
        "total": int,
        "items": List[AppTableRecord],
    }

    def __init__(self, d=None):
        self.has_more: Optional[bool] = None
        self.page_token: Optional[str] = None
        self.total: Optional[int] = None
        self.items: Optional[List[AppTableRecord]] = None
        init(self, d, self._types)

    @staticmethod
    def builder() -> "ListAppTableRecordResponseBodyBuilder":
        return ListAppTableRecordResponseBodyBuilder()


class ListAppTableRecordResponseBodyBuilder(object):
    def __init__(self) -> None:
        self._search_app_table_record_response_body = SearchAppTableRecordResponseBody()

    def has_more(self, has_more: bool) -> "ListAppTableRecordResponseBodyBuilder":
        self._search_app_table_record_response_body.has_more = has_more
        return self

    def page_token(self, page_token: str) -> "ListAppTableRecordResponseBodyBuilder":
        self._search_app_table_record_response_body.page_token = page_token
        return self

    def total(self, total: int) -> "ListAppTableRecordResponseBodyBuilder":
        self._search_app_table_record_response_body.total = total
        return self

    def items(
        self, items: List[AppTableRecord]
    ) -> "ListAppTableRecordResponseBodyBuilder":
        self._search_app_table_record_response_body.items = items
        return self

    def build(self) -> "SearchAppTableRecordResponseBody":
        return self._search_app_table_record_response_body
