# Code generated by Lark OpenAPI.

from typing import *
from baseopensdk.core.construct import init
from baseopensdk.core.model import BaseResponse
from .search_app_table_record_response_body import SearchAppTableRecordResponseBody


class SearchAppTableRecordResponse(BaseResponse):
    _types = {"data": SearchAppTableRecordResponseBody}

    def __init__(self, d=None):
        super().__init__(d)
        self.data: Optional[SearchAppTableRecordResponseBody] = None
        init(self, d, self._types)
