name: Backend CI

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

permissions:
  contents: write

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'use-bitable'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - run: npm install --frozen-lockfile
        working-directory: ./client
      - name: Build Test
        run: npm run build
        working-directory: ./client
      - name: Test
        run: npm run test
        working-directory: ./client