name: Backend CI

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

permissions:
  contents: write

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'use-bitable'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.7.3"
          enable-cache: true
      - run: uv sync
        working-directory: ./server
      - name: Test
        run: pytest
        working-directory: ./server