name: CI

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.repository == 'use-bitable/Excel-Compare-and-Import'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm install --frozen-lockfile
      - name: Build Test
        run: npm run build
      - name: Test
        run: npm run test